// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Auth struct {
	ID        string
	Userid    string
	Token     string
	Ipaddress sql.NullString
	Useragent sql.NullString
	Expiresat sql.NullTime
}

type User struct {
	ID        string
	Username  string
	Password  string
	Createdat sql.NullTime
	Updatedat sql.NullTime
}
