// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgresDB

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID        pgtype.UUID
	Userid    pgtype.UUID
	Token     string
	Ipaddress pgtype.Text
	Useragent pgtype.Text
	Expiresat pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Password  string
	Createdat pgtype.Timestamptz
	Updatedat pgtype.Timestamptz
}
